apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditchecklistmoduledeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditChecklistModule
  template:
    metadata:
      labels:
        app: AuditChecklistModule
    spec:
      containers:
      - name: auditchecklistrepos
        image: 856691auditchecklistcr.azurecr.io/auditchecklistrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: auditchecklistmodule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditChecklistModule